/**
 * Citation Parser & Audit Validator Module for ASTra.
 *
 * Parses LLM-generated answer text to extract inline citation tags:
 *   [filePath:startLine-endLine]  or  [filePath:startLine]
 *
 * Audits every extracted citation against the actual retrieved CodeChunks metadata.
 * Valid citations are populated with matching source code snippets; hallucinated
 * citations are flagged and logged for security and transparency.
 */

import type { Citation, CitationValidationResult, CodeChunk } from "@/types";

// Regex matching [filePath:startLine-endLine] or [filePath:startLine]
const CITATION_REGEX = /\[([a-zA-Z0-9_./\-]+):(\d+)(?:-(\d+))?\]/g;

/**
 * Parse and validate inline citations from LLM answer text against retrieved chunks.
 *
 * @param answerText - Raw answer string generated by LLM.
 * @param retrievedChunks - Chunks that were passed to the LLM context.
 * @returns CitationValidationResult containing valid Citations array and invalid tag strings.
 */
export function parseAndValidateCitations(
  answerText: string,
  retrievedChunks: CodeChunk[]
): CitationValidationResult {
  const validCitations: Citation[] = [];
  const invalidCitations: string[] = [];
  const seenCitationKeys = new Set<string>();

  // Reset regex state
  CITATION_REGEX.lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = CITATION_REGEX.exec(answerText)) !== null) {
    const rawTag = match[0];
    const filePath = match[1];
    const startLine = parseInt(match[2], 10);
    const endLine = match[3] ? parseInt(match[3], 10) : startLine;

    const citationKey = `${filePath}:${startLine}-${endLine}`;
    if (seenCitationKeys.has(citationKey)) continue;
    seenCitationKeys.add(citationKey);

    // Audit against retrieved chunks
    const matchingChunk = retrievedChunks.find((c) => {
      const pathsMatch =
        c.filePath.toLowerCase() === filePath.toLowerCase() ||
        c.filePath.toLowerCase().endsWith(filePath.toLowerCase());

      // Line range overlap check
      const linesOverlap =
        startLine <= c.endLine && endLine >= c.startLine;

      return pathsMatch && linesOverlap;
    });

    if (matchingChunk) {
      // Extract specific snippet lines if possible
      const chunkLines = matchingChunk.content.split(/\r?\n/);
      const relativeStart = Math.max(0, startLine - matchingChunk.startLine);
      const relativeEnd = Math.min(
        chunkLines.length,
        endLine - matchingChunk.startLine + 1
      );

      const snippetLines = chunkLines.slice(relativeStart, relativeEnd);
      const snippet = snippetLines.join("\n").trim() || matchingChunk.content.slice(0, 150);

      validCitations.push({
        filePath: matchingChunk.filePath,
        startLine,
        endLine,
        snippet,
      });
    } else {
      console.warn(
        `⚠️ Warning: Invalid/hallucinated citation tag "${rawTag}" found in LLM response.`
      );
      invalidCitations.push(rawTag);
    }
  }

  return {
    citations: validCitations,
    invalidCitations,
  };
}
